import type { Metadata } from "next";
import {
  Epilogue,
  Inter,
  Montserrat,
  Montserrat_Alternates,
} from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memora App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>{children}
      <Toaster />
      </body>
    </html>
  );
}
